#!/usr/bin/env bash
# Runs ON the Radxa CM4 (Armbian, vendor kernel) as root, after setup-camera.sh and its reboot. Installs
# Rockchip's 3A engine (rkaiq_3A_server, RK3576 build) with an IMX219 tuning file for the RK3576 ISP and
# runs it as the systemd service microduck-rkaiq. Without this the ISP output is dark and green: no
# exposure loop, no white balance, no gamma. Safe to re-run.
#
#   scp -r scripts/compute/setup-camera-3a.sh scripts/compute/camera root@microduck.local:
#   ssh root@microduck.local bash setup-camera-3a.sh          # install and start
#   ssh root@microduck.local bash setup-camera-3a.sh --check  # is it running and doing 3A?
#
# What it installs and why (details in docs/camera-setup.md section 7):
#   - libdrm2 and camera-engine-rkaiq 6.8.0-rk3576 from Radxa's rk3576-bookworm pool (the deb is
#     downloaded unless camera/camera_engine_rkaiq_rk3576_arm64.deb is supplied). The deb's own
#     sysinit-time unit is disabled: it starts before the camera nodes exist.
#   - /etc/iqfiles/imx219_rpi-camera-v2_default.json, generated by camera/make-imx219-iq.py from Radxa's
#     RK3588 IMX219 tuning. The name is <sensor>_<module>_<lens> from the overlay.
#   - /usr/local/lib/rkaiq-sched-shim.so: the engine's statistics thread asks for SCHED_RR, which this
#     kernel (CONFIG_RT_GROUP_SCHED) refuses to every systemd service; without the thread there is no 3A.
#   - /usr/local/bin/rkaiq-stream-resync: re-applies sensor exposure after each stream start (issue 452).
#   - /usr/local/sbin/microduck-rkaiq.sh and microduck-rkaiq.service tying it together.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CAM="${HERE}/camera"
DEB=camera_engine_rkaiq_rk3576_arm64.deb
DEB_URL="https://radxa-repo.github.io/rk3576-bookworm/pool/main/c/camera-engine-rkaiq/${DEB}"
DEB_VERSION=6.8.0-rk3576
IQ=imx219_rpi-camera-v2_default.json
UNIT=microduck-rkaiq

say()  { printf '>> %s\n' "$*"; }
die()  { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

check() {
  echo "--- packages:"; dpkg-query -W -f='${Package} ${Version} ${Status}\n' camera-engine-rkaiq libdrm2 2>/dev/null || echo "(not installed)"
  echo "--- tuning file:"; ls -l /etc/iqfiles/${IQ} 2>/dev/null || echo "(missing)"
  echo "--- service:"; systemctl is-enabled ${UNIT} 2>/dev/null || true; systemctl is-active ${UNIT} 2>/dev/null || true
  echo "--- vendor unit rkaiq_3A (should be disabled):"; systemctl is-enabled rkaiq_3A 2>/dev/null || true
  local pid; pid="$(pgrep -x rkaiq_3A_server || true)"
  if [[ -n "$pid" ]]; then
    echo "--- engine pid ${pid}, cgroup $(cut -d: -f3 /proc/${pid}/cgroup)"
    echo "--- engine threads (xc:isp_3a_stats must appear while a stream is running; xc:isp_sof_poll always):"
    cat /proc/${pid}/task/*/comm | sort | uniq -c
  else
    echo "--- engine not running"
  fi
  echo "--- resync helper: $(pgrep -a -f /usr/local/bin/rkaiq-stream-resync || echo not running)"
  echo "--- last log lines:"; journalctl -u ${UNIT} -n 12 --no-pager -o cat 2>/dev/null || true
  echo "--- test from the Mac: scripts/compute/camera/snap.sh --isp   (auto exposed, colour corrected)"
}
if [[ "${1:-}" == "--check" ]]; then check; exit 0; fi

# 1. Preconditions.
[[ $EUID -eq 0 ]] || die "run as root (ssh root@... or sudo)"
[[ "$(uname -r)" == *vendor* ]] || die "not the Armbian vendor kernel; rkisp only exists there"
for f in rkaiq-sched-shim.c rkaiq-stream-resync.c microduck-rkaiq.sh "${IQ}"; do
  [[ -f "${CAM}/${f}" ]] || die "missing ${CAM}/${f}; copy the camera/ directory alongside this script"
done
command -v gcc >/dev/null || die "gcc missing (apt install gcc)"
command -v media-ctl >/dev/null || die "media-ctl missing (apt install v4l-utils)"
ls /dev/media* >/dev/null 2>&1 || die "no /dev/media*: run setup-camera.sh and reboot first, and check the camera is connected"

# 2. Packages.
if ! dpkg-query -W -f='${Status}' libdrm2 2>/dev/null | grep -q 'install ok installed'; then
  say "installing libdrm2 (the engine links libdrm.so.2)"
  DEBIAN_FRONTEND=noninteractive apt-get install -y -qq libdrm2 >/dev/null
fi
if [[ "$(dpkg-query -W -f='${Status} ${Version}' camera-engine-rkaiq 2>/dev/null || true)" != "install ok installed ${DEB_VERSION}" ]]; then
  WORK="$(mktemp -d)"; trap 'rm -rf "$WORK"' EXIT
  if [[ -f "${CAM}/${DEB}" ]]; then
    cp "${CAM}/${DEB}" "${WORK}/${DEB}"; say "using ${CAM}/${DEB}"
  else
    say "downloading ${DEB_URL}"
    curl -fsSL -o "${WORK}/${DEB}" "$DEB_URL" || wget -q -O "${WORK}/${DEB}" "$DEB_URL" || die "could not download ${DEB}; put it in ${CAM}/ and re-run"
  fi
  DEBIAN_FRONTEND=noninteractive dpkg -i "${WORK}/${DEB}" >/dev/null
  say "installed camera-engine-rkaiq $(dpkg-query -W -f='${Version}' camera-engine-rkaiq)"
else
  say "camera-engine-rkaiq ${DEB_VERSION} already installed"
fi
# The deb enables rkaiq_3A.service at sysinit, before udev has created the camera nodes, and its init
# script backgrounds the engine behind a pipe. Ours replaces it.
systemctl disable --now rkaiq_3A.service >/dev/null 2>&1 || true

# 3. Shim and helper.
gcc -O2 -shared -fPIC -o /usr/local/lib/rkaiq-sched-shim.so "${CAM}/rkaiq-sched-shim.c" -ldl
gcc -O2 -o /usr/local/bin/rkaiq-stream-resync "${CAM}/rkaiq-stream-resync.c"
say "built /usr/local/lib/rkaiq-sched-shim.so and /usr/local/bin/rkaiq-stream-resync"

# 4. Tuning file. Group video so a non-root tuning tool can replace it later.
install -d -m 2775 -g video /etc/iqfiles
install -m 0644 "${CAM}/${IQ}" "/etc/iqfiles/${IQ}"
say "installed /etc/iqfiles/${IQ}"

# 5. Service.
install -m 0755 "${CAM}/microduck-rkaiq.sh" /usr/local/sbin/microduck-rkaiq.sh
[[ -f /etc/default/microduck-rkaiq ]] || cat > /etc/default/microduck-rkaiq <<'EOF'
# Sensor mode the 3A engine is sized for; consumers must stream this mode (camera-setup.md 4a).
# 3280x2464 is the full frame at 21 fps (crop 3280x1845 at top 310 in the ISP for 16:9 720p).
# 1920x1080 is the 30 fps centre crop with a 39 degree horizontal field of view.
SENSOR_MODE=3280x2464
EOF
cat > /etc/systemd/system/${UNIT}.service <<EOF
[Unit]
Description=Microduck head camera 3A engine (rkaiq, IMX219 on the RK3576 ISP)
After=systemd-udevd.service

[Service]
Type=simple
ExecStart=/usr/local/sbin/microduck-rkaiq.sh
Restart=on-failure
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable ${UNIT}.service >/dev/null 2>&1
systemctl restart ${UNIT}.service
sleep 3
say "service ${UNIT}: $(systemctl is-active ${UNIT})"
journalctl -u ${UNIT} -n 6 --no-pager -o cat 2>/dev/null || true
say "done. Check with: bash $(basename "$0") --check ; picture from the Mac: scripts/compute/camera/snap.sh --isp"
